### ISSUE TITLE
Unstable positions

### ISSUE THREAD

**Issue by tommhuth** [react-spring/use-cannon#98] opened 2020-07-10 08:28 UTC
I made a simple Codebox example where the camera and the player move forward at at fixed speed, and the path the player is on is automatically generated in front of the player, and removed behind him. However the position of the boxes seem unstable: for some frames (when a body is removed) the positions seem suddenly out of sync, before snapping into place again. Check this out: https://codesandbox.io/s/unstable-boxes-5w9vq (jump by clicking). 

Since it happens super fast, here are screenshots right before and after:
 
Right before
<img width="745" alt="Screen Shot 2020-07-10 at 10 20 20" src="https://user-images.githubusercontent.com/1224941/87133074-1a945380-c297-11ea-92e9-3448d56f8f63.png">

Positions off (last yellow block now gone, new yellow in front)
<img width="704" alt="Screen Shot 2020-07-10 at 10 19 53" src="https://user-images.githubusercontent.com/1224941/87133088-1e27da80-c297-11ea-9696-a5c7520cc1bf.png">

Snapping back
<img width="755" alt="Screen Shot 2020-07-10 at 10 20 07" src="https://user-images.githubusercontent.com/1224941/87133090-1ec07100-c297-11ea-8c99-fdff9512841f.png">

Is there something going on with `use-cannon` here, or is there something obvious i'm missing? I've used the same approach with a custom Cannon implementation, based off of React Three Fibre's own example, and had no similar problems there.

**Comment by codynova** [comment] 2020-07-10 08:41
This is a duplicate of #96 

I moved your other thread to discussions until we can verify an actual issue. Please use that thread.

**Closed by codynova** 2020-07-10 08:41 UTC
Labels: duplicate
