### ISSUE TITLE
Can't resolve 'worker_thread'

### ISSUE THREAD

**Issue by gtolarc** [react-spring/use-cannon#86] opened 2020-06-12 03:59 UTC
Starting from v0.45, the following error occurs during initial loading.

```
warn  - ./node_modules/use-cannon/dist/Provider-ff1cad56.js
Module not found: Can't resolve 'worker_threads' in './node_modules/use-cannon/dist'
```

**Comment by drcmda** [comment] 2020-06-12 06:56
@codynova this is part of the bundle ... do you know where this comes from?

```jsx
...
var WorkerClass = null;

try {
    var WorkerThreads =
        typeof module !== 'undefined' && typeof module.require === 'function' && module.require('worker_threads') ||
        typeof __non_webpack_require__ === 'function' && __non_webpack_require__('worker_threads') ||
        typeof require === 'function' && require('worker_threads');
    WorkerClass = WorkerThreads.Worker;
} catch(e) {} // eslint-disable-line

function decodeBase64(base64, enableUnicode) {
...
```

**Comment by drcmda** [comment] 2020-06-12 07:01
do, it seems worker-loader has added node support:

```jsx
function createBase64WorkerFactory$2(base64, sourcemapArg, enableUnicodeArg) {
    if (isNodeJS()) {
        return createBase64WorkerFactory(base64, sourcemapArg, enableUnicodeArg);
    }
    return createBase64WorkerFactory$1(base64, sourcemapArg, enableUnicodeArg);
}
```

`createBase64WorkerFactory` relies on worker_threads. but that's silly, why would they do that unasked.

**Comment by drcmda** [comment] 2020-06-12 07:02
the issue is known: https://github.com/darionco/rollup-plugin-web-worker-loader/issues/20

**Comment by drcmda** [comment] 2020-06-12 07:06
should be fixed

**Closed** 2020-06-12 07:05 UTC
